# Generated by Django 5.0.1 on 2024-02-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='found_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_date', models.DateField()),
                ('location', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('shape', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
    ]
