# Generated by Django 5.0.1 on 2024-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_contactenquiry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost_item',
            name='category',
            field=models.CharField(default='default_value_here', max_length=50),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
