# Generated by Django 5.0.1 on 2024-03-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_lost_item_category_alter_lost_item_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost_item',
            name='category',
            field=models.CharField(choices=[('purse', 'Purse/Bag'), ('phone', 'Phone'), ('bottle', 'Bottle'), ('watch', 'Watch'), ('umbrella', 'Umbrella'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
