# Generated by Django 5.0.1 on 2024-03-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_lost_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost_item',
            old_name='item_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='lost_item',
            old_name='item_name',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='lost_item',
            name='category',
        ),
        migrations.AddField(
            model_name='lost_item',
            name='item_category',
            field=models.CharField(choices=[('purse', 'Purse/Bag'), ('phone', 'Phone'), ('bottle', 'Bottle'), ('watch', 'Watch'), ('umbrella', 'Umbrella'), ('others', 'Others')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lost_item',
            name='specific_mark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='shape',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
