# Generated by Django 3.1.14 on 2024-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_item_date_lost_item_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found_item',
            old_name='item_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='found_item',
            name='item_name',
        ),
        migrations.AddField(
            model_name='found_item',
            name='item_category',
            field=models.CharField(choices=[('purse', 'Purse/Bag'), ('phone', 'Phone'), ('bottle', 'Bottle'), ('watch', 'Watch'), ('umbrella', 'Umbrella'), ('others', 'Others')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='found_item',
            name='material',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='found_item',
            name='specific_mark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='found_item',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='found_item',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='found_item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='found_item',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='found_item',
            name='shape',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='found_item',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
