# Generated by Django 4.2.6 on 2024-04-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_found_item_image_lost_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_item',
            name='user_email',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost_item',
            name='user_email',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
